name: 'Build preparation'
description: 'Prepares the environment for building'

inputs:
  browsers:
    description: 'Space-separated list of browsers to install with Playwright'
  github-token:
    description: 'GitHub token for fetching versions'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
    - name: Install npm dependencies
      run: npm ci
      shell: bash
    # TODO: swicth back to `arduino/setup-protoc@v3` after it supports Node 24
    - name: Install Protoc
      uses: StackOverflowExcept1on/setup-protoc@f5f2b9afbd3d14a13caf3e0b4f6c109ed8f3e89c # node24
      with:
        repo-token: ${{ inputs.github-token }}
    - name: Generate protos
      run: npm run genproto
      shell: bash
    - name: Generate dev keys
      run: npm run genkeys
      shell: bash
    - name: Install Playwright browsers
      if: ${{ inputs.browsers != '' }}
      run: npx playwright install --with-deps ${{ inputs.browsers }}
      shell: bash
