# Based on: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Angular CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read

jobs:
  buildprep:
    name: Prepare code
    uses: rdamazio/efis-editor/.github/workflows/build-prep.yml@main

  build:
    name: Code builds
    runs-on: ubuntu-latest
    needs: buildprep

    steps:
      - name: Fetch prepared artifacts
        uses: atos-actions/download-artifact@d1e3e6643ea5c245d882277db031c31739e83d3e
        with:
          name: prepared-source
      - name: Build
        run: npm run build

  test:
    name: Tests pass
    runs-on: ubuntu-latest
    needs: buildprep

    steps:
      - name: Fetch prepared artifacts
        uses: atos-actions/download-artifact@d1e3e6643ea5c245d882277db031c31739e83d3e
        with:
          name: prepared-source
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium firefox
      - name: Run tests
        # Attempt to re-run in case there's flakiness.
        run: npm run test:headless || npm run test:headless
        env:
          # Clear CHROME_BIN because otherwise @angular/build:unit-test will apply it
          # as launchOptions.executablePath for ALL Playwright browsers (including Firefox)
          # which causes Firefox to attempt executing the google-chrome binary.
          CHROME_BIN: ''

      - name: Upload test results
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: test-results
          path: |
            test-results/
            **/__screenshots__/
          if-no-files-found: ignore
          retention-days: 30

  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    needs: buildprep

    steps:
      - name: Fetch prepared artifacts
        uses: atos-actions/download-artifact@d1e3e6643ea5c245d882277db031c31739e83d3e
        with:
          name: prepared-source
      - name: Install Playwright browser
        # Coverage only works on Chromium.
        run: npx playwright install --with-deps chromium
      - name: Run test coverage
        run: npm run test:coverage
      - name: Upload coverage results
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: coverage-results
          path: |
            coverage/
          if-no-files-found: ignore
          retention-days: 30

  lint:
    name: Linters
    runs-on: ubuntu-latest
    needs: buildprep
    steps:
      - name: Fetch prepared artifacts
        uses: atos-actions/download-artifact@d1e3e6643ea5c245d882277db031c31739e83d3e
        with:
          name: prepared-source
      - run: npm run lint
      - run: npm run lint:actions
      - run: npm run format
      - uses: codespell-project/actions-codespell@8f01853be192eb0f849a5c7d721450e7a467c579 # v2
        with:
          path: src
      - uses: marocchino/validate-dependabot@d8ae5c0d03dd75fbd0ad5f8ab4ba8101ebbd4b37 # v3
        id: validate

  dependabot:
    name: Dependabot auto-merge
    runs-on: ubuntu-latest
    needs: [build, test, coverage, lint]
    if: github.event_name == 'pull_request' && github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'rdamazio/efis-editor'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@21025c705c08248db411dc16f3619e6b5f9ea21a
        # TODO: Remove after this action migrates
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Enable auto-merge for Dependabot PRs
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor'
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
