# Based on: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Angular CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.7.3"
          cache: 'npm'
      - name: Install npm dependencies
        run: npm ci
      - name: Install ProtoC
        uses: arduino/setup-protoc@v3
      - name: Generate protos
        run: |
          protoc \
            --proto_path=src/model/proto \
            --plugin=protoc-gen-ts=node_modules/@protobuf-ts/plugin/bin/protoc-gen-ts \
            --ts_out=gen/ts \
            src/model/proto/*.proto
      - name: Build
        run: npm run build --if-present
      - name: Run tests
        run: npm run test:headless
