# Based on: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Angular CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: "21.7.3"
          cache: 'npm'
      - run: npm ci
      - run: find node_modules
      - run: |
          mkdir -p gen/ts
          node_modules/@protobuf-ts/protoc/installed/protoc-26.1-osx-aarch_64/bin/protoc \
            --proto_path=${workspaceRoot}/src/model/proto \
            --plugin=protoc-gen-ts=node_modules/@protobuf-ts/plugin/bin/protoc-gen-ts \
            --ts_out=gen/ts"
      - run: npm run build --if-present
      - run: npm test
